/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vinaya_os;

import java.awt.Frame;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ankita Singh
 */
public class DeadLock_Bankers extends javax.swing.JFrame {
    DefaultTableModel model1, model2,model3,model4 ;
    static int max[][];
    static int need[][];
    static int available[][];
    static int allocation[][];
    static int np,nr,i,j;

    /**
     * Creates new form DeadLock_Bankers
     */
    public DeadLock_Bankers() {
        initComponents();
        model1 = new DefaultTableModel();
        model2 = new DefaultTableModel();
        model3 = new DefaultTableModel();
        model4 = new DefaultTableModel();
        res_alloc_mat.setModel(model1);
        max_mat.setModel(model2);
        avail_mat.setModel(model3);
        need_mat.setModel(model4);
        res_alloc_matrix.setVisible(false);
        max_matrix.setVisible(false);
        avail_matrix.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Minimize = new javax.swing.JLabel();
        Restore = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        res_num = new javax.swing.JTextField();
        process_num = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        res_alloc_matrix = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        res_alloc_mat = new javax.swing.JTable();
        max_matrix = new javax.swing.JLabel();
        avail_matrix = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        max_mat = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        avail_mat = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        need_matrix = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        need_mat = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(243, 243, 243));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Minimize.setBackground(new java.awt.Color(255, 255, 255));
        Minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Minimize_Window_32px.png"))); // NOI18N
        Minimize.setOpaque(true);
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        jPanel2.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 40, 40));

        Restore.setBackground(new java.awt.Color(255, 255, 255));
        Restore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Restore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Restore_Window_32px.png"))); // NOI18N
        Restore.setOpaque(true);
        Restore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestoreMouseClicked(evt);
            }
        });
        jPanel2.add(Restore, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 0, 40, 40));

        Close.setBackground(new java.awt.Color(255, 255, 255));
        Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Delete_32px.png"))); // NOI18N
        Close.setOpaque(true);
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        jPanel2.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1445, 0, 40, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 40));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel3.setText("Available Matrix");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 260, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel4.setText("No. of Processes");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 260, 40));

        res_num.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jPanel1.add(res_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 110, 40));

        process_num.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jPanel1.add(process_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 110, 40));

        jButton4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton4.setText("Edit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 110, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel5.setText("No. of Resources");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 260, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel6.setText("Resource Alloc. Matrix");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 260, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel7.setText("Maximum Matrix");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 260, 40));

        jButton5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton5.setText("Enter");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 110, 40));

        jButton6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton6.setText("Edit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 110, 40));

        jButton7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton7.setText("Edit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 110, 40));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel8.setText("Generate Need Matrix");
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 260, 40));

        jButton8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton8.setText("View");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 110, 40));

        jButton9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton9.setText("View");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, 110, 40));

        jButton10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton10.setText("View");
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 660, 110, 40));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel9.setText("Check Status");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 260, 40));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel10.setText("See Safe Sequence");
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 260, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 480, 800));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        res_alloc_matrix.setBackground(new java.awt.Color(255, 255, 255));
        res_alloc_matrix.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        res_alloc_matrix.setText("Resource Allocation Matrix");
        res_alloc_matrix.setOpaque(true);
        jPanel4.add(res_alloc_matrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 30));

        res_alloc_mat.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        res_alloc_mat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        res_alloc_mat.setRowHeight(40);
        res_alloc_mat.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(res_alloc_mat);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1000, 310));

        max_matrix.setBackground(new java.awt.Color(255, 255, 255));
        max_matrix.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        max_matrix.setText("Maximum Matrix");
        max_matrix.setOpaque(true);
        jPanel4.add(max_matrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 30));

        avail_matrix.setBackground(new java.awt.Color(255, 255, 255));
        avail_matrix.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        avail_matrix.setText("Available Matrix");
        avail_matrix.setOpaque(true);
        jPanel4.add(avail_matrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 30));

        max_mat.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        max_mat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        max_mat.setRowHeight(40);
        max_mat.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(max_mat);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1000, 310));

        avail_mat.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        avail_mat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        avail_mat.setRowHeight(40);
        avail_mat.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(avail_mat);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1000, 310));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 1020, 340));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        need_matrix.setBackground(new java.awt.Color(255, 255, 255));
        need_matrix.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        need_matrix.setText("Need Matrix");
        need_matrix.setOpaque(true);
        jPanel5.add(need_matrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 30));

        need_mat.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        need_mat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        need_mat.setRowHeight(40);
        jScrollPane2.setViewportView(need_mat);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1000, 270));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 1020, 310));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1000, 60));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane6.setViewportView(jTextArea2);

        jPanel6.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1000, 60));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 690, 1020, 150));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton1.setText("Simulate");
        jButton1.setEnabled(false);
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 10, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 120, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 840, 1500, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MinimizeMouseClicked

    private void RestoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestoreMouseClicked
        // TODO add your handling code here:
        this.setSize(1500, 900);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_RestoreMouseClicked

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        res_alloc_matrix.setVisible(false);
        max_matrix.setVisible(false);
        avail_matrix.setVisible(true);
        jScrollPane1.setVisible(false);
        jScrollPane4.setVisible(false);
        jScrollPane3.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        np=Integer.parseInt(process_num.getText());
        nr=Integer.parseInt(res_num.getText());
        max=new int[np][nr];
        need=new int[np][nr];
        available=new int[1][nr];
        allocation=new int[np][nr];
        model1.setColumnCount(nr);
        model1.setRowCount(np);
        model2.setColumnCount(nr);
        model2.setRowCount(np);
        model4.setColumnCount(nr);
        model4.setRowCount(np);
        model3.setColumnCount(nr);
        model3.setRowCount(1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        max_matrix.setVisible(false);
        avail_matrix.setVisible(false);
        res_alloc_matrix.setVisible(true);
        jScrollPane3.setVisible(false);
        jScrollPane1.setVisible(true);
        jScrollPane4.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        res_alloc_matrix.setVisible(false);
        avail_matrix.setVisible(false);
        max_matrix.setVisible(true);
        jScrollPane3.setVisible(false);
        jScrollPane1.setVisible(false);
        jScrollPane4.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<np;i++){

            for(int j=0;j<nr;j++){
                allocation[i][j]=Integer.parseInt(res_alloc_mat.getValueAt(i, j).toString());
                max[i][j]=Integer.parseInt(max_mat.getValueAt(i, j).toString());
                need[i][j]=max[i][j]-allocation[i][j];
                model4.setValueAt(need[i][j], i, j);
            }

        }
        for( i=0;i<nr;i++){

            available[0][i]=Integer.parseInt(avail_mat.getValueAt(0, i).toString());
            System.out.println(available[0][i]);
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:3
        int c=0;

        boolean status[]=new boolean[np];
        System.out.println(status[0]);
        while(c<np){

            boolean allocated=false;

            for( i=0;i<np;i++){

                if( !status[i] && check(i)){

                    status[i]=true;

                    allocated=true;

                    c++;

                    System.out.println("Allocated process : "+i);
                    jTextArea1.setText(jTextArea1.getText()+"Allocated process : "+i+"\n");
                    for( j=0;j<nr;j++){

                        available[0][j]=available[0][j]+allocation[i][j];

                    }

                }

            }

            if(!allocated) break; //if no allocation

        }

        if(c==np) //if all processes are allocated
        {
            System.out.println("\nSafely allocated");
            jTextArea2.setText("Safely Allocated...");
        }
        else
        {
            System.out.println("All proceess cant be allocated safely");
            jTextArea2.setText("All processes cant be allocated safely...");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

public boolean check(int p)
{
    for(int i=0;i<nr;i++)
    {
        if(available[0][i]<need[p][i])
        {
            return false;   
        }
    }
    return true;
}
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeadLock_Bankers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeadLock_Bankers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeadLock_Bankers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeadLock_Bankers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeadLock_Bankers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel Restore;
    private javax.swing.JTable avail_mat;
    private javax.swing.JLabel avail_matrix;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTable max_mat;
    private javax.swing.JLabel max_matrix;
    private javax.swing.JTable need_mat;
    private javax.swing.JLabel need_matrix;
    private javax.swing.JTextField process_num;
    private javax.swing.JTable res_alloc_mat;
    private javax.swing.JLabel res_alloc_matrix;
    private javax.swing.JTextField res_num;
    // End of variables declaration//GEN-END:variables
}
