/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vinaya_os;

import java.awt.Frame;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
/**
 *
 * @author Ankita Singh
 */
public class Process_Synchronization extends javax.swing.JFrame {
    static DefaultTableModel model1,model2,model3;
    static int size;
    Timer timer1,timer2;
    ActionListener action1,action2;
    static int in=0,out=-1;
    static int i=-1;
    static final int BUFFER_SIZE=10;
    static int buffer[];
    static int counter=0,counter1=0;
    /**
     * Creates new form Process_Synchronization
     */
    public Process_Synchronization() {
        initComponents();
        model1 = new DefaultTableModel();
        model2 = new DefaultTableModel();
        model3 = new DefaultTableModel();
        Producer_table.setModel(model1);
        Buffer_table.setModel(model2);
        Consumer_table.setModel(model3);
        buffer=new int[BUFFER_SIZE];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Minimize = new javax.swing.JLabel();
        Restore = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        item_num = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Producer_table = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Buffer_table = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Consumer_table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(243, 243, 243));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Minimize.setBackground(new java.awt.Color(255, 255, 255));
        Minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Minimize_Window_32px.png"))); // NOI18N
        Minimize.setOpaque(true);
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        jPanel2.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 40, 40));

        Restore.setBackground(new java.awt.Color(255, 255, 255));
        Restore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Restore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Restore_Window_32px.png"))); // NOI18N
        Restore.setOpaque(true);
        Restore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestoreMouseClicked(evt);
            }
        });
        jPanel2.add(Restore, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 0, 40, 40));

        Close.setBackground(new java.awt.Color(255, 255, 255));
        Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Delete_32px.png"))); // NOI18N
        Close.setOpaque(true);
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        jPanel2.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1445, 0, 40, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 40));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel2.setText("INPUT :");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 180, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel3.setText("No. of Items");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 180, 50));

        item_num.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jPanel1.add(item_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 170, 50));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 410, 490));

        jButton4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton4.setText("Set");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 170, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 450, 790));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel5.setText("PRODUCER :");
        jLabel5.setOpaque(true);
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 180, 50));

        Producer_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Producer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Producer_table.setEnabled(false);
        Producer_table.setRowHeight(63);
        Producer_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Producer_table);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 990, 100));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel6.setText("BUFFER :");
        jLabel6.setOpaque(true);
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 180, 50));

        Buffer_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Buffer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Buffer_table.setEnabled(false);
        Buffer_table.setRowHeight(63);
        Buffer_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(Buffer_table);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 990, 100));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel7.setText("CONSUMER :");
        jLabel7.setOpaque(true);
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 180, 50));

        Consumer_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Consumer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Consumer_table.setEnabled(false);
        Consumer_table.setRowHeight(63);
        Consumer_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(Consumer_table);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 990, 100));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 1050, 790));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 50));

        jButton6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton6.setText("Simulate");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 170, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 830, 1500, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MinimizeMouseClicked

    private void RestoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestoreMouseClicked
        // TODO add your handling code here:
        this.setSize(1500, 900);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_RestoreMouseClicked

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
        size=Integer.parseInt(item_num.getText());
        model1.setColumnCount(size);
        model1.setRowCount(1);
        model2.setColumnCount(10);
        model2.setRowCount(1);
        model3.setColumnCount(size);
        model3.setRowCount(1);
        jButton4.setEnabled(false);
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog (null, "Error in number format: Reenter the number");
            item_num.setText("");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Vinaya_Home ob=new Vinaya_Home();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Create producer thread

        jButton6.setEnabled(false);
        action1 = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if(counter<size)
            {
                while((in+1)%(BUFFER_SIZE)==out);

                counter++;
                buffer[in]=counter;
                jTextArea1.setText(jTextArea1.getText()+"Producer produced : "+buffer[in]+"\n");
                model1.setValueAt(buffer[in], 0, counter-1);
                model2.setValueAt(buffer[in], 0, counter-1);
                in=(in+1)%BUFFER_SIZE;
                int bufferStatus;
                if(out<in)
                {
                    bufferStatus=in-out;
                }
                else if(out>in)
                {
                    bufferStatus=BUFFER_SIZE-(out-in);
                }
                else
                {
                    bufferStatus=0;
                }
                jTextArea1.setText(jTextArea1.getText()+"Buffer Status After Producing : "+bufferStatus+"\n");
                if(counter==1)
                    out++;
                timer1.setDelay(1000);
                }
                else
                {
                    timer1.stop();
                }
            }
        };
        action2 = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if(counter1<size){
                while(in==out);

                counter1++;
                jTextArea1.setText(jTextArea1.getText()+"Consumer Consumed : "+buffer[out]+"\n");
                model3.setValueAt(buffer[out], 0, counter1-1);
                model2.setValueAt(0, 0, counter1-1);
                out=(out+1)%BUFFER_SIZE;

                int bufferStatus;
                if(out<in)
                {
                    bufferStatus=in-out;
                }
                else if(out>in)
                {
                    bufferStatus=BUFFER_SIZE-(out-in);
                }
                else
                {
                    bufferStatus=0;
                }
                jTextArea1.setText(jTextArea1.getText()+"Buffer Status After Consuming : "+bufferStatus+"\n");
                }
                else
                {
                    timer2.stop();
                }
            }
        };

        timer1 = new Timer(1000, action1);
        timer2 = new Timer(2000, action2);

        timer1.start();timer2.start();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Process_Synchronization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Process_Synchronization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Process_Synchronization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Process_Synchronization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Process_Synchronization().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Buffer_table;
    private javax.swing.JLabel Close;
    public javax.swing.JTable Consumer_table;
    private javax.swing.JLabel Minimize;
    private javax.swing.JTable Producer_table;
    private javax.swing.JLabel Restore;
    private javax.swing.JTextField item_num;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
