
package vinaya_os;
import java.awt.Frame;
import java.awt.GraphicsEnvironment;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ankita Singh
 */
public class Vinaya_Home extends javax.swing.JFrame {
    int xx,xy;
    /**
     * Creates new form Vinaya_Home
     */
    public Vinaya_Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LandingPanel = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        Maximize = new javax.swing.JLabel();
        Restore = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        LandingPanel.setPreferredSize(new java.awt.Dimension(1500, 800));
        LandingPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LandingPanelMouseDragged(evt);
            }
        });
        LandingPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LandingPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LandingPanelMouseReleased(evt);
            }
        });
        LandingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close.setBackground(new java.awt.Color(255, 255, 255));
        Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Delete_32px.png"))); // NOI18N
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        LandingPanel.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1445, 0, 40, 40));

        Maximize.setBackground(new java.awt.Color(255, 255, 255));
        Maximize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Maximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Maximize_Window_32px.png"))); // NOI18N
        Maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaximizeMouseClicked(evt);
            }
        });
        LandingPanel.add(Maximize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1396, 0, 40, 40));

        Restore.setBackground(new java.awt.Color(255, 255, 255));
        Restore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Restore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Restore_Window_32px.png"))); // NOI18N
        Restore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestoreMouseClicked(evt);
            }
        });
        LandingPanel.add(Restore, new org.netbeans.lib.awtextra.AbsoluteConstraints(1347, 0, 40, 40));

        Minimize.setBackground(new java.awt.Color(255, 255, 255));
        Minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Minimize_Window_32px.png"))); // NOI18N
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        LandingPanel.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1298, 0, 40, 40));

        jLabel1.setBackground(new java.awt.Color(232, 232, 232));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Process Scheduling");
        jLabel1.setMaximumSize(new java.awt.Dimension(450, 350));
        jLabel1.setMinimumSize(new java.awt.Dimension(450, 350));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(450, 350));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        LandingPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 454, 389));

        jLabel2.setBackground(new java.awt.Color(232, 232, 232));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Deadlock");
        jLabel2.setMaximumSize(new java.awt.Dimension(450, 350));
        jLabel2.setMinimumSize(new java.awt.Dimension(450, 350));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(450, 350));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        LandingPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 438, 454, 390));

        jLabel3.setBackground(new java.awt.Color(232, 232, 232));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Page Replacement");
        jLabel3.setMaximumSize(new java.awt.Dimension(450, 350));
        jLabel3.setMinimumSize(new java.awt.Dimension(450, 350));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(450, 350));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        LandingPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(986, 438, 454, 390));

        jLabel4.setBackground(new java.awt.Color(232, 232, 232));
        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Process Synchronization");
        jLabel4.setMaximumSize(new java.awt.Dimension(450, 350));
        jLabel4.setMinimumSize(new java.awt.Dimension(450, 350));
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(450, 350));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        LandingPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(986, 40, 454, 389));

        jLabel5.setBackground(new java.awt.Color(232, 232, 232));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Process Creation");
        jLabel5.setMaximumSize(new java.awt.Dimension(450, 350));
        jLabel5.setMinimumSize(new java.awt.Dimension(450, 350));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(450, 350));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        LandingPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 460, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Choose...");
        jLabel6.setMaximumSize(new java.awt.Dimension(450, 350));
        jLabel6.setMinimumSize(new java.awt.Dimension(450, 350));
        jLabel6.setPreferredSize(new java.awt.Dimension(450, 350));
        LandingPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 40, 454, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LandingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LandingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void MaximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaximizeMouseClicked
        // TODO add your handling code here:
        GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
        this.setMaximizedBounds(env.getMaximumWindowBounds());
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
    }//GEN-LAST:event_MaximizeMouseClicked

    private void RestoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestoreMouseClicked
        // TODO add your handling code here:
        this.setSize(1500, 800);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_RestoreMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MinimizeMouseClicked

    private void LandingPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LandingPanelMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_LandingPanelMouseDragged

    private void LandingPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LandingPanelMousePressed
        // TODO add your handling code here:
        setOpacity(0.8f);
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_LandingPanelMousePressed

    private void LandingPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LandingPanelMouseReleased
        // TODO add your handling code here:
        setOpacity(1.0f);
    }//GEN-LAST:event_LandingPanelMouseReleased

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Vinaya_ProcessCreate obj=new Vinaya_ProcessCreate();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Vinaya_ProcessSchedule obj=new Vinaya_ProcessSchedule();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        Vinaya_ProcessSynch obj=new Vinaya_ProcessSynch();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Vinaya_Deadlock obj=new Vinaya_Deadlock();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Vinaya_PageRep obj=new Vinaya_PageRep();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vinaya_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vinaya_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vinaya_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vinaya_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vinaya_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close;
    private javax.swing.JPanel LandingPanel;
    private javax.swing.JLabel Maximize;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel Restore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
